name: Python CI & Publish

on:
  push:
    branches:
      - main
      - build_fixes
    tags:
      - 'v*'  # trigger publish on version tags
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Cache Poetry dependencies
      - name: Cache Poetry & pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m venv .venv
          source ./.venv/bin/activate
          poetry install --sync --no-ansi

      # Run tests
      - name: Run Tests
        run: |
          set +e
          ./tools/run_tests.sh 'not integration'
          EXIT_CODE=$?
          echo "pytest exit code: $EXIT_CODE"
          exit $EXIT_CODE

      # Run linters
      - name: Run Pylint
        run: |
          ./tools/run_pylint.sh

      - name: Run Black
        run: |
          ./tools/run_black.sh

      - name: Run Isort
        run: |
          ./tools/run_isort.sh

      - name: Run Mypy
        run: |
          ./tools/run_mypy.sh

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')  # only run on version tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build twine

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
